# Generated by Django 4.1.5 on 2023-03-26 19:44

import dashboard_app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Nom")),
                ("last_name", models.CharField(max_length=255, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(
                        max_length=200,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "i_agree",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Terms and conditions",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Patient", "Patient"),
                            ("Docteur", "Docteur"),
                            ("Admin", "Admin"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Rôle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", dashboard_app.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Sujet")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "hour",
                    models.CharField(
                        choices=[
                            ("8h:00mn", "8h:00mn"),
                            ("8h:30mn", "8h:30mn"),
                            ("9h:00mn", "9h:00mn"),
                            ("9h:30mn", "9h:30mn"),
                            ("10h:00mn", "10h:00mn"),
                            ("10h:30mn", "10h:30mn"),
                            ("11h:00mn", "11h:00mn"),
                            ("11h:30mn", "11h:30mn"),
                            ("12h:00mn", "12h:00mn"),
                            ("12h:30mn", "12h:30mn"),
                            ("13h:00mn", "13h:00mn"),
                            ("13h:30mn", "13h:30mn"),
                            ("14h:00mn", "14h:00mn"),
                            ("14h:30mn", "14h:30mn"),
                            ("15h:00mn", "15h:00mn"),
                            ("15h:30mn", "15h:30mn"),
                            ("16h:00mn", "16h:00mn"),
                            ("16h:30mn", "16h:30mn"),
                            ("17h:00mn", "17h:00mn"),
                        ],
                        max_length=25,
                        verbose_name="Horaire",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("read", models.BooleanField(default=False, verbose_name="Lu")),
                ("active", models.BooleanField(default=True, verbose_name="Est actif")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="AppointmentPrescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Poids"
                    ),
                ),
                (
                    "body_temperature",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Température Corporelle",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Prix payé"
                    ),
                ),
                (
                    "description",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Est actif")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="AppointmentSymptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nom"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Est actif")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nom"),
                ),
                (
                    "unity_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Prix Unitaire",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="Quantité"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Reduction"
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nom Commercial"
                    ),
                ),
                (
                    "genetic_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nom Générique"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("active", models.BooleanField(default=True, verbose_name="Est actif")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nom"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Est actif")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="Product/%Y/%m/%d/",
                        verbose_name="Fichier(png, jpeg, jpg)",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nom"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Est actif")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nom"),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=255, null=True, verbose_name="Pays"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ville"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Site Web"
                    ),
                ),
                (
                    "facebook_link",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Lien Facebook",
                    ),
                ),
                (
                    "twitter_link",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Lien Twitter",
                    ),
                ),
                (
                    "instagram_link",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Lien  Instagram",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Est actif")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, default=1, null=True, verbose_name="Quantité"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Total(cfa)"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("active", models.BooleanField(default=True, verbose_name="Est actif")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier",
                        to="dashboard_app.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Service/%Y/%m/%d/",
                        verbose_name="Image",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_category",
                        to="dashboard_app.servicecategory",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, null=True, verbose_name="Quantité"
                    ),
                ),
                (
                    "unity_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Prix Unitaire",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Total",
                    ),
                ),
                (
                    "recu",
                    models.FileField(
                        upload_to="Recu/%Y/%m/%d/", verbose_name="Fichier(pdf,image)"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Est actif")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_product",
                        to="dashboard_app.product",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Images/%Y/%m/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de Naissance"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=255, null=True, verbose_name="Pays"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ville"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Masculin", "Masculin"), ("Feminin", "Feminin")],
                        max_length=100,
                        null=True,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Profession"
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Lien de Facebook",
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Lien de Instagram",
                    ),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Lien de Twitter",
                    ),
                ),
                (
                    "linked_in",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Lien de LinkedIn",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Est actif")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_Image",
                to="dashboard_app.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_category",
                to="dashboard_app.productimage",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock",
                to="dashboard_app.stock",
            ),
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Prénom"
                    ),
                ),
                (
                    "reg_no",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="Numero de Registration",
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Profession"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Masculin", "Masculin"), ("Feminin", "Feminin")],
                        max_length=100,
                        null=True,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de Naissance"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        unique=True,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=255, null=True, verbose_name="Pays"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ville"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Address"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Est actif")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, null=True, verbose_name="Sujet"),
                ),
                ("read", models.BooleanField(default=False, verbose_name="Lu")),
                ("active", models.BooleanField(default=True, verbose_name="Est actif")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_appointment",
                        to="dashboard_app.appointment",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
    ]
