# Generated by Django 4.1.5 on 2023-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_app", "0003_alter_appointment_age_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="Images/%Y/%m/", verbose_name="Photo"
            ),
        ),
    ]
