# Generated by Django 4.1.5 on 2023-02-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_app", "0005_servicecategory_alter_user_role_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="photo",
        ),
    ]
