# Generated by Django 4.1.5 on 2023-01-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "logo",
                    models.ImageField(upload_to="Partner/%Y/%m/", verbose_name="Logo"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Website URL",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Status")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
    ]
