# Generated by Django 4.1.5 on 2023-02-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing_app", "0005_product_photo"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="photo",),
    ]
