# Generated by Django 4.1.5 on 2023-02-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing_app", "0005_remove_blogcomment_website"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Patients",
        ),
        migrations.DeleteModel(
            name="Pharmacist",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="supplier",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
