# Generated by Django 4.1.5 on 2023-02-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_app", "0007_supplier_stock_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="Images/%Y/%m/", verbose_name="Photo"
            ),
        ),
    ]
