# Generated by Django 4.1.5 on 2023-02-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_app", "0009_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Nom"),
        ),
    ]
