# Generated by Django 4.1.5 on 2023-02-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_app", "0011_doctor_pharmacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacy",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="Images/%Y/%m/", verbose_name="Photo"
            ),
        ),
    ]
