# Generated by Django 4.1.5 on 2023-02-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_app", "0012_pharmacy_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacy",
            name="specialization",
            field=models.CharField(max_length=255, verbose_name="Categorie"),
        ),
    ]
